exclude_patterns:
  - "**/*.spec.js"
  - "**/public/"
  - "**/vendor/"
  - "**/node_modules/"
  - "**/.github/"
  - ".github/"
  - "*.md"
  - "*.json"
  - "**/database/"
  - "**/coverage"
plugins:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          count_threshold: 5
          mass_threshold: 75
